models/lecture.py
from .db import db

class Lecture(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    week = db.Column(db.String(80), nullable=False)
    timetable = db.Column(db.Integer, nullable=False)
    
    def to_dict(self):
        return {
        "id": self.id,
        "title": self.title,
        "week": self.week,
        "timetable": self.timetable,
    }

models/todo.py
from .db import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    lecture_id = db.Column(db.Integer, db.ForeignKey('lecture.id'), nullable=False)
    description = db.Column(db.String(128), nullable=False)
    deadline = db.Column(db.DateTime, nullable=False)

routes/absence.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_login import current_user, login_required
from models import  UserLectureRelation, Lecture, User
from models import data
from models.db import db

# Blueprintの作成
absence_bp = Blueprint('absence', __name__, url_prefix='/absence')

# all_user_lectures = [
#     {"id": 1, "user_id": 1, "lecture_id": 1, "absenceCount": 1},
#     {"id": 2, "user_id": 1, "lecture_id": 2, "absenceCount": 2},
#     # 他のユーザーと講義のデータ
# ]

# mylecture = [
#                 { "id":1,"title": "情報システム概論", "week": "月曜日", },
#                 { "id":2,"title": "オブジェクト演習", "week": "火曜日",}
#                 ]

# all_lectures = [
#     {"id": 1, "title": "情報システム概論", "week": "月曜日", "timetable": 1},
#     {"id": 2, "title": "オブジェクト演習", "week": "火曜日", "timetable": 2},
#     {"id": 3, "title": "データベース論", "week": "水曜日", "timetable": 3},
#     # 他の講義データも追加可能
# ]


@absence_bp.route('/result', methods=['GET', 'POST'])
@login_required
def result():
    
    user_id = current_user.get_id()
    
    
    if request.method == 'POST':
        absence_count = request.form.get('absence')
        lecture = request.form.get('lecture')
        print(absence_count)
        print(lecture)

        # user_lecture_relation を取得
        user_lecture_relation = UserLectureRelation.query.filter_by(
        user_id=user_id, lecture_id= int(lecture)).first()

        # user_lecture_relation が None でないことを確認
        if user_lecture_relation:
            user_lecture_relation.absence_count = absence_count
            db.session.commit()
        else:
            user_lecture_relation = UserLectureRelation(
                user_id=user_id,
                lecture_id=lecture_id,
                absence_count=absence_count
            )
            db.session.add(user_lecture_relation)
            db.session.commit()
            
        return redirect(url_for('home.index'))
            
    elif request.method == 'GET':
        
        lecture_id = request.args.get('lecture')
        print(lecture_id)
        
        selected_lecture = db.session.query(
            Lecture.id, Lecture.title, UserLectureRelation.absence_count
        ).join(UserLectureRelation, Lecture.id == UserLectureRelation.lecture_id) \
        .filter(UserLectureRelation.user_id == user_id, Lecture.id == lecture_id).first()
        print(selected_lecture)
        return render_template('absence_result.html', lecture=selected_lecture)


    # if request.method == 'POST':
    #     name = request.form['name']
    #     absence = request.form['absence']
    #     # query = MySubject.update(absence=absence).where(MySubject.name == name)
    #     # query.execute()
    #     return redirect(url_for('absence.result'))


@absence_bp.route('/', methods=['GET'])
@login_required

def index():
    
    # 本来はDBから講義データを取得する
    mylectureData = get_absences(current_user.get_id())
    
    return render_template('absence.html', lectures=mylectureData)
  
@absence_bp.route('/absences', methods=['GET']) 
@login_required 
def absences():
    
    if request.method == 'GET':
        week = request.args.get('weekday')
        
        user_id = current_user.get_id()
        
        # DBからuserとweekが一致する講義データを取得する
        mylectureData = db.session.query(
            Lecture.id, Lecture.title, Lecture.week
        ).join(UserLectureRelation, Lecture.id == UserLectureRelation.lecture_id) \
        .filter(UserLectureRelation.user_id == user_id, Lecture.week == week).all()
        
        
        
        return render_template('absence.html', subjects= mylectureData, day=week)       
        
        
        
def get_absences(user_id):
    
    print(db)
    
    #SQLAlchemy用
    
    absences = db.session.query(
        UserLectureRelation.id, Lecture.title, UserLectureRelation.absence_count,UserLectureRelation.lecture_id
    ).join(Lecture, Lecture.id == UserLectureRelation.lecture_id) \
    .filter(UserLectureRelation.user_id == user_id).all()
            
    
    # 仮データ
    # absences = [{
    #     "absence_id": 1,
    #     "lecture_title": "情報システム概論",
    #     "absence_count": 1
    # }, {
    #     "absence_id": 2,
    #     "lecture_title": "オブジェクト演習",
    #     "absence_count": 2
    # }]
    
    
    
    return absences

routes/home.py
# Blueprintの作成
from flask import Blueprint, render_template, session, redirect, url_for # type: ignore
from flask_login import login_required,current_user # type: ignore

from routes.todo import get_todo
from .absence import get_absences

home_bp = Blueprint('home', __name__, url_prefix='/home')

@home_bp.route('/')
@login_required
def index():
    
    # セッションからusernameを取得
    username = current_user.get_id()
    print(username)

    # usernameがセッションに保存されていない場合、ログインページにリダイレクトすることもできます
    if username:
        # ユーザーに対応する欠席情報を取得（例：ユーザーごとに欠席情報があると仮定）
        absences = get_absences(username)
        
        # dbからtodoListを取得するapiを呼び出す
        
        todoList = get_todo(username)
    else:
        absences = []
        todoList = []
    
    return render_template('home.html', absences=absences,todoList=todoList)    

routes/id.py
# Blueprintの作成
from flask import Blueprint, render_template, request, url_for, flash, redirect, session # type: ignore
from models.user import User
from flask_login import login_user


id_bp = Blueprint('id', __name__, url_prefix='/id')

@id_bp.route('')
def index():
    return render_template('id.html')

# @id_bp.route('/success')
# def success():
#     return render_template('success.html')  # 登録成功ページ

@id_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user_id = request.form['user']
        password = request.form['pass']
        
        # user = User.get_or_none(User.user_id == user_id)  # Userモデルの検索例
        
        user = User.query.filter_by(username=user_id).first()
        
        if user is None:
            print("ユーザーが見つかりません")
            # ユーザーが見つからない場合の処理
            return redirect(url_for('id.index'))  # id Blueprint のトップページにリダイレクト
        
        if user.password == password:  # パスワード一致確認
            # ログイン成功処理
            # session['user_id'] = user_id  # セッションに保存
            login_user(user, remember=True)
            print('ログイン成功')
            return redirect(url_for('home.index'))  # ホームページへリダイレクト
        else:
            # ログイン失敗処理
            print('ログイン失敗')
            return redirect(url_for('id.index'))  # id Blueprint のトップページにリダイレクト

    
    # ログインページを表示
    return render_template('id_login.html')

        
    

routes/lecture.py
from flask import Blueprint, flash, render_template, request, redirect, session, url_for
from flask_login import login_required
from models.db import db
from models.lecture import Lecture
from models.userLectureRelation import UserLectureRelation

lecture_bp = Blueprint('lectures', __name__, url_prefix='/lectures')

# 特定の曜日・時限に対応する講義を返す
def get_classes_by_day_and_time(day, time):
    return Lecture.query.filter_by(week=day, timetable=time).all()

@lecture_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    day = request.args.get('day')
    time = request.args.get('time')
    
    classes = []
    if day and time:
        try:
            time = int(time)  # 時限は整数に変換
            classes = get_classes_by_day_and_time(day, time)
        except ValueError:
            pass  # 時限が整数でない場合は無視

    # セッションに保存された選択された講義を取得
    local_subject_ids = session.get('local_subjects', [])
    local_subjects = [Lecture.query.filter_by(id=subject_id).first().to_dict() for subject_id in local_subject_ids]

    return render_template(
        'lecture.html',
        selected_day=day,
        selected_time=time,
        classes=[lecture.to_dict() for lecture in classes],
        local_subjects=local_subjects,
    )

@lecture_bp.route('/add', methods=['POST'])
@login_required
def add():
    try:
        subject_id = int(request.form.get('lecture'))  # lecture_idを取得
    except (TypeError, ValueError):
        flash("無効な講義IDです", "error")
        return redirect(url_for('lectures.index'))

    # 対応する講義を取得
    subject = Lecture.query.filter_by(id=subject_id).first()

    if subject:
        
        myLecture = db.session.query(
            UserLectureRelation.lecture_id,
            UserLectureRelation.user_id
        ).filter(UserLectureRelation.lecture_id == subject_id).first()
        
        if myLecture:
            flash("すでに登録されている講義です", "error")
            return redirect(url_for('lectures.index'))
        
        # セッションに講義IDを追加
        
        localsubject_ids = session.get('local_subjects', [])
        
        if subject_id not in localsubject_ids:
            
            localsubject_ids.append(subject_id)
            session['local_subjects'] = localsubject_ids
        
        
        

    else:
        flash("講義が見つかりません", "error")
        
    return redirect(url_for('lectures.index'))



@lecture_bp.route('/select_class', methods=['POST'])
@login_required
def select_class():
    lecture_id = request.form.get('lecture')
    
    if lecture_id:
        # ID を元に該当する講義を取得
        lecture = Lecture.query.filter_by(id=lecture_id).first()
        
        if lecture:
            # セッションに講義IDを追加
            local_subject_ids = session.get('local_subjects', [])
            if lecture.id not in local_subject_ids:
                local_subject_ids.append(lecture.id)
                session['local_subjects'] = local_subject_ids
                
        else:
            flash("講義が見つかりません", "error")
    
    return redirect(url_for('lecture_result.index'))

routes/lecture_result.py
from flask import Blueprint, flash, render_template, request, redirect, session, url_for
from flask_login import current_user, login_required # type: ignore

from models.db import db
from models.lecture import Lecture
from models.userLectureRelation import UserLectureRelation

lectureResult_bp = Blueprint('lecture_result', __name__, url_prefix='/lectures/result')

@lectureResult_bp.route('/')
@login_required
def index():
    # セッションから保存された講義情報を取得
    local_subject_ids = session.get('local_subjects', [])
    
    # IDからLectureオブジェクトを再取得
    local_subjects = [Lecture.query.get(subject_id).to_dict() for subject_id in local_subject_ids]

    # 辞書のIDを基にソートする
    sorted_subjects = sorted(local_subjects, key=lambda x: x['id'])

    # 同じ曜日と時限の講義を検出
    for lecture in sorted_subjects:
        lecture['highlight'] = any(
            other['id'] != lecture['id'] and other['week'] == lecture['week'] and other['timetable'] == lecture['timetable']
            for other in sorted_subjects
        )

    return render_template('lecture_result.html', local_subjects=sorted_subjects)

@lectureResult_bp.route('/delete', methods=['POST'])
@login_required
def delete():
    lecture_id = request.form.get('lecture')  # 削除対象の講義IDを取得
    
    if lecture_id:
        lecture_id = int(lecture_id)  # IDを整数に変換
        local_subject_ids = session.get('local_subjects', [])
        
        # 削除対象を検索
        updated_subjects = [lec_id for lec_id in local_subject_ids if lec_id != lecture_id]
        session['local_subjects'] = updated_subjects  # セッションを更新
    
        return redirect(url_for('lecture_result.index'))
  
    else:
        flash("Invalid subject ID", "error")
        return redirect(url_for('lecture_result.index'))

    
@lectureResult_bp.route('/save', methods=['POST'])
@login_required
def save():
    # 講義情報を保存する処理
    local_subject_ids = session.get('local_subjects', [])
    
    for subject_id in local_subject_ids:
        # DBからLectureオブジェクトを取得
        lecture = db.session.query(Lecture).get(subject_id)
        
        if lecture:
            
            # 重複登録を防ぐためにUserLectureRelationを取得
            user_lecture_relation = UserLectureRelation.query.filter_by(
                user_id=current_user.get_id(),
                lecture_id=lecture.id
            ).first()
            
            if user_lecture_relation:
                continue

            new_user_lecture = UserLectureRelation(
                user_id=current_user.get_id(),
                lecture_id=lecture.id,
                absence_count=0
            )
            db.session.add(new_user_lecture)
            db.session.commit()
    
    return redirect(url_for('home.index'))

routes/todo.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_login import current_user, login_required
from models.lecture import Lecture
from models.todo import Todo
from models.db import db
from models.userLectureRelation import UserLectureRelation

todos_bp = Blueprint('todos', __name__, url_prefix='/todos')

@todos_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    if request.method == 'GET':
        user_id = current_user.get_id()
        
        # DBからuser_idに一致する講義データを取得
        user_lecture_relations = UserLectureRelation.query.filter_by(user_id=user_id).all()
        lecture_ids = [relation.lecture_id for relation in user_lecture_relations]
        lectures = Lecture.query.filter(Lecture.id.in_(lecture_ids)).all()
        
        return render_template('todo.html', classes=lectures)
    
    elif request.method == 'POST':
        
        deadline = datetime.strptime(request.form['date'], '%Y-%m-%d')
        
        
        user_id = current_user.get_id()
        lecture_id = request.form['lecture']
        description = request.form['todo']
        deadline = deadline
        
        # DBからidに一致する講義データを取得
        lecture_title = Lecture.query.filter_by(id=lecture_id).first().title
        
        todoData = {
            "user_id": user_id,
            "lecture_id": lecture_id,
            "lecture_title": lecture_title,
            "description": description,
            "deadline": deadline
        }
        
        # sessionにtodoDataを保存
        session['todoData'] = todoData
        
        return render_template('todo_result.html', todoData=todoData)

@todos_bp.route('/result', methods=['POST', 'DELETE'])
@login_required
def result():
    if request.method == 'POST':
        # データ取得
        todoData = session.get('todoData')
        
        # DBに保存する処理
        newTodo = Todo(
            user_id=todoData['user_id'],
            lecture_id=todoData['lecture_id'],
            description=todoData['description'],
            deadline=todoData['deadline']
        )
        db.session.add(newTodo)
        db.session.commit()
        
        return redirect(url_for('home.index'))
    
    elif request.method == 'DELETE':
        todo_id = request.form.get('todo_id')
        todo = Todo.query.filter_by(id=todo_id).first()
        if todo:
            db.session.delete(todo)
            db.session.commit()
        
        return redirect(url_for('todos.index'))
    
    return render_template('todo.html')


def get_todo(user_id):

    # 本来はDBから講義データを取得する

    
    todos = db.session.query(
        Todo.id, Lecture.title, Todo.description, Todo.deadline
    ).join(Lecture, Todo.lecture_id == Lecture.id).filter(Todo.user_id == user_id).all()
            
    return todos

templates/absence.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/absence.css" />
    <title>欠席登録</title>
</head>
<body>
    <h1>欠席登録</h1>

    <!-- 曜日選択フォーム -->
    <form method="get" action="{{ url_for('absence.absences') }}">
        <label for="weekday">曜日を選択:</label>
        <select id="weekday" name="weekday" required>
            <option value="">--選択してください--</option>
            <option value="月曜日" {% if day == "月曜日" %}selected{% endif %}>月曜日</option>
            <option value="火曜日" {% if day == "火曜日" %}selected{% endif %}>火曜日</option>
            <option value="水曜日" {% if day == "水曜日" %}selected{% endif %}>水曜日</option>
            <option value="木曜日" {% if day == "木曜日" %}selected{% endif %}>木曜日</option>
            <option value="金曜日" {% if day == "金曜日" %}selected{% endif %}>金曜日</option>
        </select>
        <br>
        <button type="submit">参照</button>
    </form>

    {% if day %}
        <h2>{{ day }}に登録されている講義</h2>

        <!-- 講義リスト -->
        {% if subjects %}
            <ul class="lecture-list">
                {% for subject in subjects %}
                    <li>
                        <a  method="get" href="{{url_for('absence.result', lecture=subject.id)}}">
                            <button type="submit" class="lecture_bt">
                                {{ subject.title }}
                            </button>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <ul class="lecture-list">
                <li>登録されている講義はありません。</li>
            </ul>
        {% endif %}
    {% endif %}
</body>
</html>

templates/absence_result.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="../static/absence.css" />

    <title>欠席数登録画面</title>
  </head>
  <body>
    <h1>欠席数登録画面</h1>

    <form method="POST" action="{{ url_for('absence.result') }}">
      <input type="hidden" name="lecture" value="{{ lecture.id }}" />
      <h2>選択した講義: {{ lecture.title }}</h2>
      <label for="absence">欠席日数:</label>
      <select id="absence" name="absence" required>
        <option value="0">0日</option>
        <option value="1">1日</option>
        <option value="2">2日</option>
        <option value="3">3日</option>
        <option value="4">4日</option>
        <option value="5">5日</option>
      </select>
      <br />
      <button type="submit">登録</button>
    </form>
    <br />
    <button onclick="window.location.href='/absence'">戻る</button>
  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="../static/home.css" />
    <title>ホーム</title>
  </head>
  <body>
    <div class="home_button">
      <h1>ホーム画面</h1>
      <form method="get" action="{{url_for('absence.index')}}">
        <button type="submit">欠席登録</button>
      </form>
      <br />
      <button type="button" onclick="location.href='/todos'">ToDo</button>
      <br />
      <button type="button" onclick="location.href='/lectures'">
        講義追加
      </button>
    </div>
    <div class="absence">
      <h2>欠席情報</h2>
      <div class="absence_list">
        {% for absence in absences %}
        <li>講義名：{{ absence.title }} - 欠席{{ absence.absence_count }}回</li>
        {% else %}
        <li>現在、欠席情報はありません。</li>
        {% endfor %}
      </div>
    </div>
    <br />
    <div class="todo">
      <h2>ToDoリスト</h2>
      <div class="todo_list">
        {% for todo in todoList %}
        <li>
          <p>講義名：{{ todo.title }}</p>
          <p>期限：{{ todo.deadline }}</p>
          <p>内容：{{ todo.description }}</p>
        </li>
        {% else %}
        <li>現在、ToDoリストはありません。</li>
        {% endfor %}
      </div>
    </div>
  </body>
</html>

templates/id.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="../static/id.css" />
    <title>ホーム</title>
  </head>
  <body>
    <header>講義情報管理アプリ 「クラストラック」</header>
    <form action="{{ url_for('user.register') }}">
      <input type="submit" value="新規ID登録" />
    </form>
    <br />
    <form action="{{ url_for('user.login') }}">
      <input type="submit" value="ログイン" />
    </form>
  </body>
</html>

templates/id_login.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="../static/id_login.css" />
    <title>ログイン</title>
  </head>
  <body>
    <h1>ログイン</h1>
    {% if ans %}
    <div
      class="message {% if 'success' in ans %}success{% else %}error{% endif %}"
    >
      {{ ans.success or ans.error }}
    </div>
    {% endif %}
    <form action="{{ url_for('user.login') }}" method="get">
      <label for="user">ユーザーID:</label>
      <input type="text" id="user" name="user" required />
      <br />
      <label for="pass">パスワード:</label>
      <input type="password" id="pass" name="password" required />
      <br />
      <input type="submit" value="ログイン" />
    </form>
    <br />
  </body>
  <!-- 初期画面はid.htmlのこと -->
  <a href="/">初期画面に戻る</a>
</html>

templates/id_new.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="../static/id_new.css" />
    <title>欠席登録</title>
  </head>
  <body>
    <h1>新規登録</h1>
    <form action="{{ url_for('user.register') }}" method="post">
      <label for="name">ユーザーID:</label>
      <input type="text" id="user" name="user" required />
      <br />
      <label for="pass">パスワード:</label>
      <input type="text" id="password" name="password" required />
      <br />
      <input type="submit" value="登録" />
    </form>
    <br />
  </body>
  <!-- 初期画面はid.htmlのこと -->
  <a href="/">初期画面に戻る</a>
</html>

templates/lecture.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>授業選択</title>
    <link rel="stylesheet" href="../static/lecture.css" />
</head>

<body>
    <!-- タイトル -->
    <div class="title">
        <h1>新規講義の追加</h1>
    </div>

    <!-- 講義選択 -->
    <form method="POST" action="{{ url_for('lectures.add') }}">
        <div class="class">
            <div class="all_text">
                <label>講義:</label>
            </div>
            {% if selected_day and selected_time %}
            {% if classes %}
            <select name="lecture" id="lecture" required>
                {% for lecture in classes %}
                <option value="{{ lecture.id }}">{{ lecture.title }}</option>
                {% endfor %}
            </select>
            <br>
            {% endif %}
            {% endif %}
        </div>
        <!-- 追加ボタン -->
        <div class="add">
            <button type="submit">追加</button>
        </div>
    </form>

    <!-- 曜日選択 -->
    <form method="get" action="/lectures">
        <div class="day_time_fontsize">
            <div class="all_text">
                <label for="day">曜日:</label>
            </div>
            <select name="day" id="day">
                <option value="">選択してください</option>
                <option value="月曜日" {% if selected_day=='月曜日' %}selected{% endif %}>月曜日</option>
                <option value="火曜日" {% if selected_day=='火曜日' %}selected{% endif %}>火曜日</option>
                <option value="水曜日" {% if selected_day=='水曜日' %}selected{% endif %}>水曜日</option>
                <option value="木曜日" {% if selected_day=='木曜日' %}selected{% endif %}>木曜日</option>
                <option value="金曜日" {% if selected_day=='金曜日' %}selected{% endif %}>金曜日</option>
            </select>
        </div>

        <!-- 時限選択 -->
        <div class="day_time_fontsize">
            <div class="all_text">
                <label for="time">時限:</label>
            </div>
            <select name="time" id="time">
                <option value="">選択してください</option>
                <option value="1" {% if selected_time=='1' %}selected{% endif %}>1時限</option>
                <option value="2" {% if selected_time=='2' %}selected{% endif %}>2時限</option>
                <option value="3" {% if selected_time=='3' %}selected{% endif %}>3時限</option>
                <option value="4" {% if selected_time=='4' %}selected{% endif %}>4時限</option>
                <option value="5" {% if selected_time=='5' %}selected{% endif %}>5時限</option>
            </select>
        </div>

        <!-- 参照ボタン -->
        <div class="reference">
            <button type="submit">参照</button>
        </div>
    </form>

    <!-- 条件に当てはまる講義のリスト -->
    <div class="reference_whitebox">
        <p>条件に当てはまる講義名</p>
        {% if classes %}
        <ul>
            {% for lecture in classes %}
            <li>{{ lecture.title }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <p>該当する講義はありません。</p>
        {% endif %}
    </div>

    <!-- 最終確認ボタン -->
    <form method="post" action="{{ url_for('lectures.select_class') }}">
        <div class="Finalconfirmation">
            <button type="submit">最終確認</button>
        </div>
    </form>

    <!-- ホームボタン -->
    <form method="post" action="{{ url_for('lecture_result.save')}}">
        <div class="home_button">
            <button type="submit">ホーム</button>
        </div>
    </form>
</body>

</html>

templates/lecture_result.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8" />
  <link rel="stylesheet" href="{{ url_for('static', filename='lecture_result.css') }}" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>最終確認</title>
</head>

<body>
  <div class="font_size">
    <h1>確認画面</h1>
  </div>

  <!-- 講義リスト表示 -->
  <div class="place">
    <div class="lecture_list" id="lectureList">
      <ul>
        {% for lecture in local_subjects %}
        <li class="{% if lecture.highlight %}highlight{% endif %}">
          <span class="lecture">講義名:</span> {{ lecture.title }} |
          <span class="lecture">曜日:</span> {{ lecture.week }} |
          <span class="lecture">時限:</span> {{ lecture.timetable }}
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <!-- 削除ボタン -->
  <form method="POST" action="{{ url_for('lecture_result.delete') }}">
    <div class="delete_select">
      <select name="lecture" id="lectureSelect">
        {% for lecture in local_subjects %}
        <option value="{{ lecture.id }}">{{ lecture.title }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="delete_button">
      <button id="deleteButton" type="submit">削除</button>
    </div>
  </form>

  <!-- 保存ボタン -->
  <form method="POST" action="{{ url_for('lecture_result.save') }}">
    <div class="add_button">
      <button type="submit">保存</button>
    </div>
  </form>

  <!-- 戻るボタン -->
  <form method="post" action="{{ url_for('lectures.index')}}">
    <div class="back_button">
      <button type="submit">戻る</button>
    </div>
  </form>

    <!-- 保存ボタン -->
    <!-- <form method="POST" action="{{ url_for('lecture_result.index') }}">
      <div class="add_button">
        <button type="submit">保存</button>
      </div>
    </form> -->
  <div class="attention">
    <p>※赤色表示されている場合は講義の曜日と時限が被ってます。どちらかを削除してください</p>
  </div>
</body>

</html>

templates/success.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>登録完了</title>
  </head>
  <body>
    <h1>登録が完了しました！</h1>
    <p>次のステップへ進むには、以下のリンクをクリックしてください。</p>
    <a href="/">初期画面に戻る</a>
  </body>
</html>

templates/todo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='todo.css') }}"
    />
    <title>ToDo Manager</title>
  </head>
  <body>
    <h1>Todoを追加</h1>
    <form method="POST" action="{{ url_for('todos.index') }}">
      <div>
        <label for="name">講義名:</label>
        <select name="lecture" id="lecture" required>
          {% for lecture in classes %}
          <option value="{{ lecture.id }}">{{ lecture.title }}</option>
          {% endfor %}
        </select>
      </div>
      <div>
        <label for="date">締切日:</label>
        <input type="date" id="date" name="date" required />
      </div>
      <div>
        <label for="todo">具体的な内容:</label>
        <textarea id="todo" name="todo" rows="4" cols="50" required></textarea>
      </div>
      <button type="submit">次へ</button>
    </form>
  </body>
</html>

templates/todo_result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='todo.css') }}"
    />
    <title>ToDo Result</title>
  </head>
  <body>
    <h1>入力内容の確認</h1>
    <form method="POST" action="{{ url_for('todos.result') }}">
      <p>講義名: {{ todoData.lecture_title }}</p>
      <p>締切日: {{ todoData.deadline }}</p>
      <p>具体的な内容: {{ todoData.description }}</p>
      <button type="submit">保存</button>
    </form>
    <a href="{{ url_for('todos.index') }}">編集</a>
  </body>
</html>